<main role="main" class="container">
    <div class="row">
        <div class="col-md-12 blog-main">
          <h3 class="pb-3 mb-4 font-italic border-bottom">
          </h3>
          <div class="blog-post">
            <h2 class="blog-post-title text-white">Disclaimer</h2>
            <p class="text-white"><b><a href="nokrijugaad.com">nokrijugaad.com</a> Website Agreement</b></p>
            <hr>
            <p class="text-white">The <a href="nokrijugaad.com">nokrijugaad.com</a> Website is an online information service provided by Nokri Jugaad, subject to your compliance with the terms and conditions set forth below.</p>
            <blockquote>
              <p class="text-white">PLEASE READ THIS DOCUMENT CAREFULLY BEFORE ACCESSING OR USING THE SITE. BY ACCESSING OR USING THE SITE, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS SET FORTH BELOW. IF YOU DO NOT WISH TO BE BOUND BY THESE TERMS AND CONDITIONS, YOU MAY NOT ACCESS OR USE THE SITE. CLASSIFIED4JOBS MAY MODIFY THIS AGREEMENT AT ANY TIME, AND SUCH MODIFICATIONS SHALL BE EFFECTIVE IMMEDIATELY UPON POSTING OF THE MODIFIED AGREEMENT ON THE SITE. YOU AGREE TO REVIEW THE AGREEMENT PERIODICALLY TO BE AWARE OF SUCH MODIFICATIONS AND YOUR CONTINUED ACCESS OR USE OF THE SITE SHALL BE DEEMED YOUR CONCLUSIVE ACCEPTANCE OF THE MODIFIED AGREEMENT.</p>
            </blockquote>
            <h2 class="text-white">1. Copyright, Licenses and Idea Submissions.</h2>
            <p class="text-white">The entire contents of the Site are protected by international copyright and trademark laws. The owner of the copyrights and trademarks are <a href="nokrijugaad.com">nokrijugaad.com</a>, its affiliates or other third party licensors. YOU MAY NOT MODIFY, COPY, REPRODUCE, REPUBLISH, UPLOAD, POST, TRANSMIT, OR DISTRIBUTE, IN ANY MANNER, THE MATERIAL ON THE SITE, INCLUDING TEXT, GRAPHICS, CODE AND/OR SOFTWARE. You may print and download portions of material from the different areas of the Site solely for your own non-commercial use provided that you agree not to change or delete any copyright or proprietary notices from the materials. You agree to grant to<a href="nokrijugaad.com">nokrijugaad.com</a> a non-exclusive, royalty-free, worldwide, perpetual license, with the right to sub-license, to reproduce, distribute, transmit, create derivative works of, publicly display and publicly perform any materials and other information (including, without limitation, ideas contained therein for new or improved products and services) you submit to any public areas of the Site (such as bulletin boards, forums and newsgroups) or by e-mail to private sector jobs by all means and in any media now known or hereafter developed. You also grant to <a href="nokrijugaad.com">nokrijugaad.com</a> the right to use your name in connection with the submitted materials and other information as well as in connection with all advertising, marketing and promotional material related thereto. You agree that you shall have no recourse against private sector jobs for any alleged or actual infringement or misappropriation of any proprietary right in your communications to <a href="nokrijugaad.com">nokrijugaad.com</a>.</p>
            <h3 class="text-white">1.1 Traffic Server TRADEMARKS.</h3>
            <p class="text-white">Publications, products, content or services referenced herein or on the Site are the exclusive trademarks or service marks of <a href="nokrijugaad.com">nokrijugaad.com</a>. Other product and company names mentioned in the Site may be the trademarks of their respective owners.</a></p>
            <h2 class="text-white">2. Use of the Site.</h2>
            <p class="text-white">You understand that, except for information or services clearly identified as being supplied by <a href="nokrijugaad.com">nokrijugaad.com</a>, Nokri Jugaad does not operate, control or endorse any information or services on the Internet in any way. Except for <a href="nokrijugaad.com">nokrijugaad.com</a> identified information or services, all information, products and services offered through the Site or on the Internet generally are offered by third parties, that are not affiliated with <a href="nokrijugaad.com">nokrijugaad.com</a>. You also understand that <a href="nokrijugaad.com">nokrijugaad.com</a> cannot and does not guarantee or warrant that files available for downloading through the Site will be free of infection or viruses, worms, Trojan horses or other code that manifest contaminating or destructive properties. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for accuracy of data input and output, and for maintaining a means external to the Site for the reconstruction of any lost data.</p>
            <p class="text-white">YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SITE AND THE INTERNET. <a href="nokrijugaad.com">nokrijugaad.com</a> PROVIDES THE SITE AND RELATED INFORMATION "AS IS" AND DOES NOT MAKE ANY EXPRESS OR IMPLIED WARRANTIES, REPRESENTATIONS OR ENDORSEMENTS WHATSOEVER (INCLUDING WITHOUT LIMITATION WARRANTIES OF TITLE OR NONINFRINGEMENT, OR THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE) WITH REGARD TO THE SERVICE, ANY MERCHANDISE INFORMATION OR SERVICE PROVIDED THROUGH THE SERVICE OR ON THE INTERNET GENERALLY, AND <a href="nokrijugaad.com">nokrijugaad.com</a> SHALL NOT BE LIABLE FOR ANY COST OR DAMAGE ARISING EITHER DIRECTLY OR INDIRECTLY FROM ANY SUCH TRANSACTION. IT IS SOLELY YOUR RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS AND USEFULNESS OF ALL OPINIONS, ADVICE, SERVICES, MERCHANDISE AND OTHER INFORMATION PROVIDED THROUGH THE SERVICE OR ON THE INTERNET GENERALLY. <a href="nokrijugaad.com">nokrijugaad.com</a> DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE OR THAT DEFECTS IN THE SERVICE WILL BE CORRECTED.</p>
            <p class="text-white">YOU UNDERSTAND FURTHER THAT THE PURE NATURE OF THE INTERNET CONTAINS UNEDITED MATERIALS SOME OF WHICH ARE SEXUALLY EXPLICIT OR MAY BE OFFENSIVE TO YOU. YOUR ACCESS TO SUCH MATERIALS IS AT YOUR RISK. <a href="nokrijugaad.com">nokrijugaad.com</a> HAS NO CONTROL OVER AND ACCEPTS NO RESPONSIBILITY WHATSOEVER FOR SUCH MATERIALS.</p>
            <h4 class="text-white">LIMITATION OF LIABILITY</h4>
            <p class="text-white">IN NO EVENT WILL <a href="nokrijugaad.com">nokrijugaad.com</a> BE LIABLE FOR (I) ANY INCIDENTAL, CONSEQUENTIAL, OR INDIRECT DAMAGES (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, BUSINESS INTERRUPTION, LOSS OF PROGRAMS OR INFORMATION, AND THE LIKE) ARISING OUT OF THE USE OF OR INABILITY TO USE THE SERVICE, OR ANY INFORMATION, OR TRANSACTIONS PROVIDED ON THE SERVICE, OR DOWNLOADED FROM THE SERVICE, OR ANY DELAY OF SUCH INFORMATION OR SERVICE. EVEN IF <a href="nokrijugaad.com">nokrijugaad.com</a> OR ITS AUTHORIZED REPRESENTATIVES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR (II) ANY CLAIM ATTRIBUTABLE TO ERRORS, OMISSIONS, OR OTHER INACCURACIES IN THE SERVICE AND/OR MATERIALS OR INFORMATION DOWNLOADED THROUGH THE SERVICE. BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES, CLASSIFIED4JOBS LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>
            <p class="text-white"><a href="nokrijugaad.com">nokrijugaad.com</a> make no representations whatsoever about any other web site which you may access through this one or which may link to this Site. When you access a other jobs website, please understand that it is independent from <a href="nokrijugaad.com">nokrijugaad.com</a>, and that <a href="nokrijugaad.com">nokrijugaad.com</a> has no control over the content on that website. In addition, a link to a <a href="nokrijugaad.com">nokrijugaad.com</a> website does not mean that <a href="nokrijugaad.com">nokrijugaad.com</a> endorses or accepts any responsibility for the content, or the use, of such web site.</p>
            <h2 class="text-white">3. Indemnification.</h2>
            <p class="text-white">You agree to indemnify, defend and hold harmless <a href="nokrijugaad.com">nokrijugaad.com</a>, its officers, directors, employees, agents, licensors, suppliers and any third party information providers to the Service from and against all losses, expenses, damages and costs, including reasonable attorneys' fees, resulting from any violation of this Agreement (including negligent or wrongful conduct) by you or any other person accessing the Service.</p>
            <h2 class="text-white">4. Third Party Rights.</h2>
            <p class="text-white">The provisions of paragraphs 2 (Use of the Service), and 3 (Indemnification) are for the benefit of <a href="nokrijugaad.com">nokrijugaad.com</a> and its officers, directors, employees, agents, licensors, suppliers, and any third party information providers to the Service. Each of these individuals or entities shall have the right to assert and enforce those provisions directly against you on its own behalf.</p>
            <h2 class="text-white">5. Term Termination.</h2>
            <p class="text-white">This Agreement may be terminated by either party without notice at any time for any reason. The provisions of paragraphs 1 (Copyright, Licenses and Idea Submissions), 2 (Use of the Service), 3 (Indemnification), 4 (Third Party Rights) and 6 (Miscellaneous) shall survive any termination of this Agreement.</p>
            <h2 class="text-white">6. Miscellaneous.</h2>
            <p class="text-white">This Agreement shall all be governed and construed in accordance with the laws of India applicable to agreements made and to be performed in India. You agree that any legal action or proceeding between <a href="nokrijugaad.com">nokrijugaad.com</a> and you for any purpose concerning this Agreement or the parties' obligations hereunder shall be brought exclusively in a federal or state court of competent jurisdiction sitting in India. Any cause of action or claim you may have with respect to the Service must be commenced within one (1) year after the claim or cause of action arises or such claim or cause of action is barred. <a href="nokrijugaad.com">nokrijugaad.com</a> failure to insist upon or enforce strict performance of any provision of this Agreement shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any provision of this Agreement. <a href="nokrijugaad.com">nokrijugaad.com</a> may assign its rights and duties under this Agreement to any party at any time without notice to you.</p>
          </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->
      </div><!-- /.row -->
    </main><!-- /.container -->